server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
  servlet:
    context-path: "/dm"

logging:
  level:
    ru.philit.mdma: debug
    org.springframework.web.servlet: debug
  charset:
    console: UTF-8
  pattern:
    console: "%d{HH:mm:ss.SSS} %clr(%5p) %-65.65(%clr(%logger{50}){cyan}) : %msg%n"